---
title: "Przetwarzanie danych w języku R i Python"
subtitle: "PD 2"
author: "Szymon Koński Michal Muzyka"
date: "27.04.2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Załadowanie potrzebnych bibliotek:
```{r message=FALSE, warning=FALSE}
library("knitr")
library("rmarkdown")
library("markdown")
library(dplyr)
library(data.table)
```

```{r strings , echo=FALSE}
options(stringsAsFactors=FALSE)
options(dplyr.summarise.inform = FALSE)
```

## Wczytanie danych
```{r loadData, echo=TRUE}
BibyclesPosts <- read.csv("bicycles/Posts.csv")
CoffeePosts <- read.csv("coffee/Posts.csv")
UkrainaPosts <- read.csv("ukraina/Posts.csv")
```

```{r loadDataTable, echo=TRUE}
BibyclesPostsDT <-data.table(BibyclesPosts)
CoffeePostsDT <-data.table(CoffeePosts)
UkrainaPostsDT <-data.table(UkrainaPosts)
```



```{r}
analyze_v1 <- function(posts) {
  questions <- posts[PostTypeId == 1, .(Id, CDate = as.POSIXct(CreationDate,format="%Y-%m-%dT%H:%M:%OS"), Title, OwnerUserId)]
  answers <- posts[PostTypeId == 2, .(Id, ParentId, CDate = as.POSIXct(CreationDate,format="%Y-%m-%dT%H:%M:%OS"), Body, OwnerUserId)]
  names(answers) <- paste0("answers_", names(answers))
  df <- questions[answers, on = c(Id = "answers_ParentId")]
  df$diff_time <- difftime(df$answers_CDate, df$CDate, units = "days")
  df <- df[, .(mint = min(diff_time), maxt = max(diff_time)), by=Id]
  df <- df[is.finite(mint)]
  diff_time_min <- df[, .(min = min(mint), max =  max(mint))]
  diff_time_max <- df[, .(min = min(maxt), max =  max(maxt))]
  res <- rbind(diff_time_min,  diff_time_max)
  colnames(res) <- c("first answer", "last answer")
  print(res)
}
analyze_v1(BibyclesPostsDT)
```